### ISSUE TITLE
Migrate to argparse

### ISSUE THREAD

**Issue by john-** [john-/ham2mon#10]
The `optparse` module is deprecated.  Migrate to `argparse`.  This  work is in progress.

Also, when debugging I noticed that the errors on ham2mon startup do not indicate what line generated the exception.  I was going to add stack trace to end of the summary messages in the exception handling.

There are currently 3 relatively minor items in this branch:

1.  Migration from `optparse` to `argparse`
2.  Stack trace included as additional exception handling information
3. `--debug` option that sends additional detail to a debug file

https://github.com/john-/ham2mon/tree/argparse

**Comment by lordmorgul** [comment]
Reviewed argparse-squashed, looks good.
For note: max demod length, channel spacing, min file size, ctcss filtering, and wide FM are not included at this branch so not args for those.

**Comment by john-** [comment]
The 'min file size' and 'max demod length' functions exist in this branch but have new names.  Also, both are now in seconds:

max demod length = max_recording (seconds)
min file size = min_recording (now in seconds)

**Comment by john-** [comment]
This is now part of main branch...closing this issue.
