### ISSUE TITLE
Auto Priority

### ISSUE THREAD

**Issue by john-** [john-/ham2mon#26]
If audio classification is enabled and channel has mostly voice, add that channel to the priority list.

I have the basics of this working and will be testing it further.

Questions:

- There probably needs to be an option to disable this?  For me that doesn't seem to be the case yet.
-  Current logic makes voice transmissions a priority.  Should there be an option to make data transmissions a priority?  Again, this would not apply to be and not sure if anyone would be interested in it.
- There currently is no save option for priority file.  This should probably be a separate enhancement.

**Comment by john-** [comment]
Basics working here:

https://github.com/john-/ham2mon/tree/auto_priority

**Comment by lordmorgul** [comment]
Great idea here.  I think generally data tends to have more defined channels, at least for use cases I would have to record it there would likely be known frequencies (WINLINK or APRS, etc).  I wouldn't use this for data and instead assign priority from file.
For voice this sounds great though.

**Comment by john-** [comment]
Thanks for the insight.

So far it seems to do a pretty good job.  Initially I was thinking I would get more voice recordings.  However, it turns out it is about the same number recorded from the the test file I replay.  What happens is the recordings are longer.  I compared by file size and it was over twice the amount of audio recorded with this option enabled.

**Comment by john-** [comment]
This is now merged into master
