### ISSUE TITLE
RTL-SDR Testing complete

### ISSUE THREAD

**Issue by lordmorgul** [john-/ham2mon#7]
This fork Master branch has now been tested with:
- RTL-SDR Blog v3 (RTL2838 DVB-T)
- RTL-SDR NOOELEC NESDR+ (RTL2838 DVB-T)

No issues noted from prior using the same command line parameters and levels from lordmorgul fork.

**Comment by john-** [comment]
Thanks!  I will update the docs at some point.

**Comment by john-** [comment]
README has been updated.
